- name: Create tomcat AWS infrastructure
  hosts: localhost
  connection: local
  roles:
    - tomcat_aws


- name: Deploy tomcat service
  hosts: webservers
  become: yes
  remote_user: ec2-user
  become_method: sudo
  environment:
    ANSIBLE_CONFIG: "ansible.cfg"
  roles:
    - tomcat

  tasks:
  
#  - copy:
#      src: /usr/share/maven3/nvnshoppingcart/target/nvnshoppingcart.war
#      dest: /usr/local/apache-tomcat-8.0.23/webapps/
#      mode: 0777
#      owner: root
#      group: root

  - name: start tomcat service
    become: true
    service: name=tomcat state=started
