---
- hosts: server
  gather_facts: yes
  user: ec2-user Server Auth
  become: true
  
  vars:
    package_name: httpd
    service_name: httpd

  tasks:
    - name:   installing {{package_name }}
      yum:    pkg={{ package_name }} state=installed
      #become: true

    - name:     start {{ service_name }} service
      service:  name={{ service_name }} state=started
      #become:   true

