---
- hosts: server  #group name from the inventory
  #user: ec2-user Server Auth
  become: true

   
  tasks:
    - name: Add a list of users
      user: name={{ item }} state=present
      with_items:
        - user1
        - user2
        - user3
